-- ====================================================
-- PDJ TROPHY 2026 — SUPABASE SINGLE SOURCE OF TRUTH SCHEMA
-- ====================================================

-- 1. PLAYERS TABLE
CREATE TABLE IF NOT EXISTS public.players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id TEXT UNIQUE,
  full_name TEXT NOT NULL,
  player_type TEXT,
  player_style TEXT,
  profession TEXT,
  phone TEXT,
  age INTEGER,
  cricheroes_id TEXT,
  image_url TEXT,
  status TEXT DEFAULT 'AVAILABLE',
  team TEXT DEFAULT '',
  points INTEGER DEFAULT 0,
  unsold_round INTEGER DEFAULT 0,
  auction_time TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TEAMS TABLE
CREATE TABLE IF NOT EXISTS public.teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name TEXT UNIQUE NOT NULL,
  logo_url TEXT DEFAULT '',
  point_limit INTEGER DEFAULT 20000,
  max_players INTEGER DEFAULT 11,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. AUCTION STATE PERSISTENCE TABLE (SINGLE ROW REGISTRY)
CREATE TABLE IF NOT EXISTS public.auction_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  current_index INTEGER DEFAULT 0,
  bidding_points INTEGER DEFAULT 2000,
  highest_team TEXT DEFAULT '',
  active_role_filter TEXT DEFAULT 'ALL',
  active_unsold_round INTEGER DEFAULT 0,
  auction_phase TEXT DEFAULT 'PRE_AUCTION',
  active_squad_display TEXT,
  theme_color TEXT DEFAULT 'green',
  break_seconds_remaining INTEGER DEFAULT 300,
  break_is_running BOOLEAN DEFAULT FALSE,
  break_is_no_timer BOOLEAN DEFAULT FALSE,
  broadcast_overlay JSONB,
  sold_animation_event JSONB,
  unsold_animation_event JSONB,
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT single_row CHECK (id = 1)
);

-- 4. AUCTION HISTORY / AUDIT LOG TABLE
CREATE TABLE IF NOT EXISTS public.auction_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_name TEXT NOT NULL,
  action TEXT NOT NULL,
  details TEXT,
  old_team TEXT,
  new_team TEXT,
  points INTEGER,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- INITIAL SEED FOR DEFAULT TEAMS (IF NOT EXISTS)
INSERT INTO public.teams (team_name, logo_url, point_limit, max_players)
VALUES
  ('Team Alpha', '', 20000, 11),
  ('Team A', '', 20000, 11),
  ('Team B', '', 20000, 11),
  ('Team C', '', 20000, 11),
  ('Team D', '', 20000, 11),
  ('Team E', '', 20000, 11)
ON CONFLICT (team_name) DO NOTHING;

-- ENABLE REALTIME ON PUBLIC TABLES
ALTER PUBLICATION supabase_realtime ADD TABLE public.players;
ALTER PUBLICATION supabase_realtime ADD TABLE public.auction_state;
ALTER PUBLICATION supabase_realtime ADD TABLE public.auction_history;
